# Generated by Django 6.0 on 2025-12-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('cost_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_unit', models.CharField(blank=True, choices=[('cp', 'Медные'), ('sp', 'Серебряные'), ('ep', 'Электрумовые'), ('gp', 'Золотые'), ('pp', 'Платиновые')], default='gp', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('size', models.TextField(verbose_name='Размер')),
                ('type', models.TextField(verbose_name='Тип')),
                ('hit_points', models.IntegerField(verbose_name='Уровни жизней')),
                ('strength', models.IntegerField(verbose_name='Сила')),
                ('dexterity', models.IntegerField(verbose_name='Ловкость')),
                ('constitution', models.IntegerField(verbose_name='Телосложение')),
                ('intelligence', models.IntegerField(verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(verbose_name='Мудрость')),
                ('charisma', models.IntegerField(verbose_name='Харизма')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('spell_range', models.TextField(verbose_name='Дальность')),
                ('duration', models.TextField(verbose_name='Продолжительность')),
                ('casting_time', models.TextField(verbose_name='Время накладывания')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('school', models.CharField(choices=[('abjuration', 'Ограждение'), ('conjuration', 'Вызов'), ('divination', 'Прорицание'), ('enchantment', 'Очарование'), ('evocation', 'Воплощение'), ('illusion', 'Иллюзия'), ('necromancy', 'Некромантия'), ('transmutation', 'Преобразование')], max_length=20, verbose_name='Школа магии')),
                ('ritual', models.BooleanField(default=False, verbose_name='Ритуал')),
                ('concentration', models.BooleanField(default=False, verbose_name='Концентрация')),
            ],
        ),
        migrations.CreateModel(
            name='Armor_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('natural', 'Природная броня'), ('armor', 'Доспехи'), ('magic', 'Магическая защита'), ('dex', 'Ловкость'), ('other', 'Другое')], default='natural', max_length=20, verbose_name='Тип брони')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_classes', to='DnDSite.monster', verbose_name='Монстр')),
            ],
            options={
                'verbose_name': 'Класс брони',
                'verbose_name_plural': 'Классы брони',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=20, verbose_name='Тип')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeds', to='DnDSite.monster')),
            ],
            options={
                'unique_together': {('monster', 'movement_type')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('V', 'Вербальный'), ('S', 'Соматический'), ('M', 'Материальный')], max_length=1)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='DnDSite.spell')),
            ],
            options={
                'unique_together': {('spell', 'type')},
            },
        ),
    ]
