# Generated by Django 6.0 on 2025-12-28 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnDSite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['is_homebrew', 'name'], 'verbose_name': 'Снаряжение', 'verbose_name_plural': 'Снаряжение'},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['is_homebrew', 'name'], 'verbose_name': 'Монстр', 'verbose_name_plural': 'Монстры'},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['is_homebrew', 'level', 'name'], 'verbose_name': 'Заклинание', 'verbose_name_plural': 'Заклинания'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='Homebrew'),
        ),
        migrations.AddField(
            model_name='monster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='monster',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='monster',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='Homebrew'),
        ),
        migrations.AddField(
            model_name='spell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_homebrew',
            field=models.BooleanField(default=False, verbose_name='Homebrew'),
        ),
    ]
