# Generated by Django 6.0 on 2026-01-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnDSite', '0003_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='material_description',
            field=models.TextField(blank=True, help_text='Описание компонента', null=True, verbose_name='Описание материала'),
        ),
    ]
