# Generated by Django 6.0 on 2026-01-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DnDSite', '0004_component_material_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speed',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='component',
            name='material_description',
        ),
    ]
